version: "3.8"
networks:
  local-dev-network:
    name: local-dev-network
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats
    networks:
      - local-dev-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
