version: "3.8"
networks:
  local-dev-network:
    name: local-dev-network
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats
    networks:
      - local-dev-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql-custom/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql-custom/pg_hba.conf

volumes:
  postgres_data:
