AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/createSession.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Timeout: 25 
      Environment:
        Variables:
          DATABASE_URL: postgresql://admin:password@postgres:5432/stats
      Events:
        CreateSessionApiPost:
          Type: Api
          Properties:
            Path: /courses/{courseId}
            Method: POST
  FetchSessionFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambdas/fetchSession.handler
        Runtime: nodejs18.x
        CodeUri: ./dist
        Timeout: 25
        Environment:
          Variables:
            DATABASE_URL: postgresql://admin:password@postgres:5432/stats
        Events:
          FetchSessionApi:
            Type: Api
            Properties:
              Path: /courses/{courseId}/sessions/{sessionId}
              Method: GET

  FetchCourseLifetimeStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/fetchCourseLifetimeStats.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Timeout: 25
      Environment:
        Variables:
          DATABASE_URL: postgresql://admin:password@postgres:5432/stats
      Events:
        FetchCourseLifetimeStatsApi:
          Type: Api
          Properties:
            Path: /courses/{courseId}
            Method: GET
