AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/createSession.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Timeout: 10
      Events:
        CreateSessionApi:
          Type: Api
          Properties:
            Path: /courses/{courseId}
            Method: POST
